name: reccelog

services:
  api:
    container_name: api
    build: .
    environment:
      DB_CONN_STRING: ${DB_CONN_STRING}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - go_cache:/root/go/pkg/mod       # dipendenze
      - go_build_cache:/root/.cache/go  # cache di compilazione
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:trixie
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    depends_on:
      migrate:
        condition: service_completed_successfully

  database:
    container_name: database
    image: postgis/postgis:18-3.6
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    container_name: migrate
    build: .
    command: goose up
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: ${DB_CONN_STRING}
      GOOSE_MIGRATION_DIR: ${GOOSE_MIGRATION_DIR}
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
  redis_data:
  go_cache:
  go_build_cache: